name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
          cache: true

      # Кэш модулей Go (ускоряет линт)
      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Устанавливаем и запускаем golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest            # можно зафиксировать версию, напр. v1.60.3
          args: >
            --timeout=5m
            --out-format=github-actions