name: Proto

on:
  pull_request:
    paths:
      - 'api/proto/**'
      - 'buf.yaml'
      - 'buf.gen.yaml'

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: buf lint
        run: buf lint

      - name: buf breaking (against main)
        run: |
          git fetch origin main:refs/remotes/origin/main
          buf breaking --against ".git#branch=origin/main"