// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: meeting_service.proto

package conference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_meeting_service_proto protoreflect.FileDescriptor

const file_meeting_service_proto_rawDesc = "" +
	"\n" +
	"\x15meeting_service.proto\x12\n" +
	"conference\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17conference/common.proto\x1a\x18conference/meeting.proto2\x81\x03\n" +
	"\x0eMeetingService\x12J\n" +
	"\x0fScheduleMeeting\x12\".conference.ScheduleMeetingRequest\x1a\x13.conference.Meeting\x12@\n" +
	"\n" +
	"GetMeeting\x12\x1d.conference.GetMeetingRequest\x1a\x13.conference.Meeting\x12Q\n" +
	"\fListMeetings\x12\x1f.conference.ListMeetingsRequest\x1a .conference.ListMeetingsResponse\x12F\n" +
	"\rCancelMeeting\x12 .conference.CancelMeetingRequest\x1a\x13.conference.Meeting\x12F\n" +
	"\rUpdateMeeting\x12 .conference.UpdateMeetingRequest\x1a\x13.conference.MeetingBGZEgithub.com/junhekdevsru/omega-zoom-no/api/proto/conference;conferenceb\x06proto3"

var file_meeting_service_proto_goTypes = []any{
	(*ScheduleMeetingRequest)(nil), // 0: conference.ScheduleMeetingRequest
	(*GetMeetingRequest)(nil),      // 1: conference.GetMeetingRequest
	(*ListMeetingsRequest)(nil),    // 2: conference.ListMeetingsRequest
	(*CancelMeetingRequest)(nil),   // 3: conference.CancelMeetingRequest
	(*UpdateMeetingRequest)(nil),   // 4: conference.UpdateMeetingRequest
	(*Meeting)(nil),                // 5: conference.Meeting
	(*ListMeetingsResponse)(nil),   // 6: conference.ListMeetingsResponse
}
var file_meeting_service_proto_depIdxs = []int32{
	0, // 0: conference.MeetingService.ScheduleMeeting:input_type -> conference.ScheduleMeetingRequest
	1, // 1: conference.MeetingService.GetMeeting:input_type -> conference.GetMeetingRequest
	2, // 2: conference.MeetingService.ListMeetings:input_type -> conference.ListMeetingsRequest
	3, // 3: conference.MeetingService.CancelMeeting:input_type -> conference.CancelMeetingRequest
	4, // 4: conference.MeetingService.UpdateMeeting:input_type -> conference.UpdateMeetingRequest
	5, // 5: conference.MeetingService.ScheduleMeeting:output_type -> conference.Meeting
	5, // 6: conference.MeetingService.GetMeeting:output_type -> conference.Meeting
	6, // 7: conference.MeetingService.ListMeetings:output_type -> conference.ListMeetingsResponse
	5, // 8: conference.MeetingService.CancelMeeting:output_type -> conference.Meeting
	5, // 9: conference.MeetingService.UpdateMeeting:output_type -> conference.Meeting
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meeting_service_proto_init() }
func file_meeting_service_proto_init() {
	if File_meeting_service_proto != nil {
		return
	}
	file_conference_common_proto_init()
	file_conference_meeting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meeting_service_proto_rawDesc), len(file_meeting_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meeting_service_proto_goTypes,
		DependencyIndexes: file_meeting_service_proto_depIdxs,
	}.Build()
	File_meeting_service_proto = out.File
	file_meeting_service_proto_goTypes = nil
	file_meeting_service_proto_depIdxs = nil
}
