// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: room_service.proto

package conference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Дополнительное сообщение для GetRoom, которого нет в room.proto
type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_room_service_proto protoreflect.FileDescriptor

const file_room_service_proto_rawDesc = "" +
	"\n" +
	"\x12room_service.proto\x12\n" +
	"conference\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17conference/common.proto\x1a\x15conference/room.proto\")\n" +
	"\x0eGetRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId2\x84\x03\n" +
	"\vRoomService\x12H\n" +
	"\n" +
	"CreateRoom\x12\x1d.conference.CreateRoomRequest\x1a\x1b.conference.GetRoomResponse\x12B\n" +
	"\aGetRoom\x12\x1a.conference.GetRoomRequest\x1a\x1b.conference.GetRoomResponse\x12H\n" +
	"\tListRooms\x12\x1c.conference.ListRoomsRequest\x1a\x1d.conference.ListRoomsResponse\x12A\n" +
	"\tCloseRoom\x12\x1c.conference.CloseRoomRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x0fCreateJoinToken\x12\".conference.CreateJoinTokenRequest\x1a#.conference.CreateJoinTokenResponseBGZEgithub.com/junhekdevsru/omega-zoom-no/api/proto/conference;conferenceb\x06proto3"

var (
	file_room_service_proto_rawDescOnce sync.Once
	file_room_service_proto_rawDescData []byte
)

func file_room_service_proto_rawDescGZIP() []byte {
	file_room_service_proto_rawDescOnce.Do(func() {
		file_room_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_service_proto_rawDesc), len(file_room_service_proto_rawDesc)))
	})
	return file_room_service_proto_rawDescData
}

var file_room_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_room_service_proto_goTypes = []any{
	(*GetRoomRequest)(nil),          // 0: conference.GetRoomRequest
	(*CreateRoomRequest)(nil),       // 1: conference.CreateRoomRequest
	(*ListRoomsRequest)(nil),        // 2: conference.ListRoomsRequest
	(*CloseRoomRequest)(nil),        // 3: conference.CloseRoomRequest
	(*CreateJoinTokenRequest)(nil),  // 4: conference.CreateJoinTokenRequest
	(*GetRoomResponse)(nil),         // 5: conference.GetRoomResponse
	(*ListRoomsResponse)(nil),       // 6: conference.ListRoomsResponse
	(*emptypb.Empty)(nil),           // 7: google.protobuf.Empty
	(*CreateJoinTokenResponse)(nil), // 8: conference.CreateJoinTokenResponse
}
var file_room_service_proto_depIdxs = []int32{
	1, // 0: conference.RoomService.CreateRoom:input_type -> conference.CreateRoomRequest
	0, // 1: conference.RoomService.GetRoom:input_type -> conference.GetRoomRequest
	2, // 2: conference.RoomService.ListRooms:input_type -> conference.ListRoomsRequest
	3, // 3: conference.RoomService.CloseRoom:input_type -> conference.CloseRoomRequest
	4, // 4: conference.RoomService.CreateJoinToken:input_type -> conference.CreateJoinTokenRequest
	5, // 5: conference.RoomService.CreateRoom:output_type -> conference.GetRoomResponse
	5, // 6: conference.RoomService.GetRoom:output_type -> conference.GetRoomResponse
	6, // 7: conference.RoomService.ListRooms:output_type -> conference.ListRoomsResponse
	7, // 8: conference.RoomService.CloseRoom:output_type -> google.protobuf.Empty
	8, // 9: conference.RoomService.CreateJoinToken:output_type -> conference.CreateJoinTokenResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_service_proto_init() }
func file_room_service_proto_init() {
	if File_room_service_proto != nil {
		return
	}
	file_conference_common_proto_init()
	file_conference_room_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_service_proto_rawDesc), len(file_room_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_service_proto_goTypes,
		DependencyIndexes: file_room_service_proto_depIdxs,
		MessageInfos:      file_room_service_proto_msgTypes,
	}.Build()
	File_room_service_proto = out.File
	file_room_service_proto_goTypes = nil
	file_room_service_proto_depIdxs = nil
}
