// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: conference/common.proto

package conference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Роли участников конференции
type Role int32

const (
	// Роль не указана
	Role_ROLE_UNSPECIFIED Role = 0
	// Ведущий конференции
	Role_ROLE_HOST Role = 1
	// Спикер конференции
	Role_ROLE_SPEAKER Role = 2
	// Участник конференции
	Role_ROLE_ATTENDEE Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_HOST",
		2: "ROLE_SPEAKER",
		3: "ROLE_ATTENDEE",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_HOST":        1,
		"ROLE_SPEAKER":     2,
		"ROLE_ATTENDEE":    3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_conference_common_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_conference_common_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_conference_common_proto_rawDescGZIP(), []int{0}
}

// Политика доступа
type AccessPolicy int32

const (
	// Политика доступа не указана
	AccessPolicy_ACCESS_POLICY_UNSPECIFIED AccessPolicy = 0
	// Публичный доступ
	AccessPolicy_ACCESS_PUBLIC AccessPolicy = 1
	// Приватный доступ
	AccessPolicy_ACCESS_PRIVATE AccessPolicy = 2
)

// Enum value maps for AccessPolicy.
var (
	AccessPolicy_name = map[int32]string{
		0: "ACCESS_POLICY_UNSPECIFIED",
		1: "ACCESS_PUBLIC",
		2: "ACCESS_PRIVATE",
	}
	AccessPolicy_value = map[string]int32{
		"ACCESS_POLICY_UNSPECIFIED": 0,
		"ACCESS_PUBLIC":             1,
		"ACCESS_PRIVATE":            2,
	}
)

func (x AccessPolicy) Enum() *AccessPolicy {
	p := new(AccessPolicy)
	*p = x
	return p
}

func (x AccessPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_conference_common_proto_enumTypes[1].Descriptor()
}

func (AccessPolicy) Type() protoreflect.EnumType {
	return &file_conference_common_proto_enumTypes[1]
}

func (x AccessPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessPolicy.Descriptor instead.
func (AccessPolicy) EnumDescriptor() ([]byte, []int) {
	return file_conference_common_proto_rawDescGZIP(), []int{1}
}

// Статус встречи
type MeetingStatus int32

const (
	// Статус встречи не указан
	MeetingStatus_MEETING_STATUS_UNSPECIFIED MeetingStatus = 0
	// Встреча запланирована
	MeetingStatus_MEETING_SCHEDULED MeetingStatus = 1
	// Встреча активна
	MeetingStatus_MEETING_ACTIVE MeetingStatus = 2
	// Встреча завершена
	MeetingStatus_MEETING_ENDED MeetingStatus = 3
	// Встреча отменена
	MeetingStatus_MEETING_CANCELED MeetingStatus = 4
)

// Enum value maps for MeetingStatus.
var (
	MeetingStatus_name = map[int32]string{
		0: "MEETING_STATUS_UNSPECIFIED",
		1: "MEETING_SCHEDULED",
		2: "MEETING_ACTIVE",
		3: "MEETING_ENDED",
		4: "MEETING_CANCELED",
	}
	MeetingStatus_value = map[string]int32{
		"MEETING_STATUS_UNSPECIFIED": 0,
		"MEETING_SCHEDULED":          1,
		"MEETING_ACTIVE":             2,
		"MEETING_ENDED":              3,
		"MEETING_CANCELED":           4,
	}
)

func (x MeetingStatus) Enum() *MeetingStatus {
	p := new(MeetingStatus)
	*p = x
	return p
}

func (x MeetingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeetingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_conference_common_proto_enumTypes[2].Descriptor()
}

func (MeetingStatus) Type() protoreflect.EnumType {
	return &file_conference_common_proto_enumTypes[2]
}

func (x MeetingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeetingStatus.Descriptor instead.
func (MeetingStatus) EnumDescriptor() ([]byte, []int) {
	return file_conference_common_proto_rawDescGZIP(), []int{2}
}

// Информация
type PageInfp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // Токен следующей страницы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfp) Reset() {
	*x = PageInfp{}
	mi := &file_conference_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfp) ProtoMessage() {}

func (x *PageInfp) ProtoReflect() protoreflect.Message {
	mi := &file_conference_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfp.ProtoReflect.Descriptor instead.
func (*PageInfp) Descriptor() ([]byte, []int) {
	return file_conference_common_proto_rawDescGZIP(), []int{0}
}

func (x *PageInfp) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Унифицированная ветка времени создания и обновления
type Audit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Время создания
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Время обновления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_conference_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_conference_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_conference_common_proto_rawDescGZIP(), []int{1}
}

func (x *Audit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Audit) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_conference_common_proto protoreflect.FileDescriptor

const file_conference_common_proto_rawDesc = "" +
	"\n" +
	"\x17conference/common.proto\x12\n" +
	"conference\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\bPageInfp\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\"}\n" +
	"\x05Audit\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*P\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_HOST\x10\x01\x12\x10\n" +
	"\fROLE_SPEAKER\x10\x02\x12\x11\n" +
	"\rROLE_ATTENDEE\x10\x03*T\n" +
	"\fAccessPolicy\x12\x1d\n" +
	"\x19ACCESS_POLICY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACCESS_PUBLIC\x10\x01\x12\x12\n" +
	"\x0eACCESS_PRIVATE\x10\x02*\x83\x01\n" +
	"\rMeetingStatus\x12\x1e\n" +
	"\x1aMEETING_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MEETING_SCHEDULED\x10\x01\x12\x12\n" +
	"\x0eMEETING_ACTIVE\x10\x02\x12\x11\n" +
	"\rMEETING_ENDED\x10\x03\x12\x14\n" +
	"\x10MEETING_CANCELED\x10\x04BGZEgithub.com/junhekdevsru/omega-zoom-no/api/proto/conference;conferenceb\x06proto3"

var (
	file_conference_common_proto_rawDescOnce sync.Once
	file_conference_common_proto_rawDescData []byte
)

func file_conference_common_proto_rawDescGZIP() []byte {
	file_conference_common_proto_rawDescOnce.Do(func() {
		file_conference_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conference_common_proto_rawDesc), len(file_conference_common_proto_rawDesc)))
	})
	return file_conference_common_proto_rawDescData
}

var file_conference_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_conference_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_conference_common_proto_goTypes = []any{
	(Role)(0),                     // 0: conference.Role
	(AccessPolicy)(0),             // 1: conference.AccessPolicy
	(MeetingStatus)(0),            // 2: conference.MeetingStatus
	(*PageInfp)(nil),              // 3: conference.PageInfp
	(*Audit)(nil),                 // 4: conference.Audit
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_conference_common_proto_depIdxs = []int32{
	5, // 0: conference.Audit.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: conference.Audit.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_conference_common_proto_init() }
func file_conference_common_proto_init() {
	if File_conference_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conference_common_proto_rawDesc), len(file_conference_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conference_common_proto_goTypes,
		DependencyIndexes: file_conference_common_proto_depIdxs,
		EnumInfos:         file_conference_common_proto_enumTypes,
		MessageInfos:      file_conference_common_proto_msgTypes,
	}.Build()
	File_conference_common_proto = out.File
	file_conference_common_proto_goTypes = nil
	file_conference_common_proto_depIdxs = nil
}
