// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: conference/room.proto

package conference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Объекты
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwenerId      string                 `protobuf:"bytes,2,opt,name=owener_id,json=owenerId,proto3" json:"owener_id,omitempty"`     // ID владельца комнаты
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // Название комнаты
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"` // Приватная комната или нет
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`                    // Вместимость комнаты
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // Время создания комнаты
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`  // Время обновления комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_conference_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetOwenerId() string {
	if x != nil {
		return x.OwenerId
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Room) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Владельцы комнат
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       // ID комнаты
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // ID пользователя
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=conference.Role" json:"role,omitempty"`   // Роль пользователя в комнате
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"` // Время присоединения к комнате
	LeftAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`       // Время выхода из комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_conference_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{1}
}

func (x *Member) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Member) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Member) GetLeftAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeftAt
	}
	return nil
}

// Запросы и ответы
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwenerId      string                 `protobuf:"bytes,1,opt,name=owener_id,json=owenerId,proto3" json:"owener_id,omitempty"`     // ID владельца комнаты
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // Название комнаты
	IsPrivate     bool                   `protobuf:"varint,3,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"` // Приватная комната или нет
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`                    // Вместимость комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_conference_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetOwenerId() string {
	if x != nil {
		return x.OwenerId
	}
	return ""
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreateRoomRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"` // Созданная комната
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_conference_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwenerId      string                 `protobuf:"bytes,1,opt,name=owener_id,json=owenerId,proto3" json:"owener_id,omitempty"`    // ID владельца комнаты
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // Количество комнат на странице
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // Токен страницы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_conference_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoomsRequest) GetOwenerId() string {
	if x != nil {
		return x.OwenerId
	}
	return ""
}

func (x *ListRoomsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoomsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`                                        // Список комнат
	NextRoomToken string                 `protobuf:"bytes,2,opt,name=next_room_token,json=nextRoomToken,proto3" json:"next_room_token,omitempty"` // Информация о странице
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_conference_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{5}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListRoomsResponse) GetNextRoomToken() string {
	if x != nil {
		return x.NextRoomToken
	}
	return ""
}

type CloseRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // ID комнаты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoomRequest) Reset() {
	*x = CloseRoomRequest{}
	mi := &file_conference_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomRequest) ProtoMessage() {}

func (x *CloseRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomRequest.ProtoReflect.Descriptor instead.
func (*CloseRoomRequest) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{6}
}

func (x *CloseRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type CreateJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`     // ID комнаты
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`     // ID пользователя
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=conference.Role" json:"role,omitempty"` // Роль пользователя в комнате
	TtlSec        int32                  `protobuf:"varint,4,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`    // Время жизни токена в секундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenRequest) Reset() {
	*x = CreateJoinTokenRequest{}
	mi := &file_conference_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenRequest) ProtoMessage() {}

func (x *CreateJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{7}
}

func (x *CreateJoinTokenRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateJoinTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateJoinTokenRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *CreateJoinTokenRequest) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

type CreateJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Токен для присоединения к комнате
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenResponse) Reset() {
	*x = CreateJoinTokenResponse{}
	mi := &file_conference_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenResponse) ProtoMessage() {}

func (x *CreateJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_conference_room_proto_rawDescGZIP(), []int{8}
}

func (x *CreateJoinTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_conference_room_proto protoreflect.FileDescriptor

const file_conference_room_proto_rawDesc = "" +
	"\n" +
	"\x15conference/room.proto\x12\n" +
	"conference\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17conference/common.proto\"\xf8\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\towener_id\x18\x02 \x01(\tR\bowenerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xce\x01\n" +
	"\x06Member\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.conference.RoleR\x04role\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x123\n" +
	"\aleft_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06leftAt\"\x7f\n" +
	"\x11CreateRoomRequest\x12\x1b\n" +
	"\towener_id\x18\x01 \x01(\tR\bowenerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_private\x18\x03 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"7\n" +
	"\x0fGetRoomResponse\x12$\n" +
	"\x04room\x18\x01 \x01(\v2\x10.conference.RoomR\x04room\"k\n" +
	"\x10ListRoomsRequest\x12\x1b\n" +
	"\towener_id\x18\x01 \x01(\tR\bowenerId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"c\n" +
	"\x11ListRoomsResponse\x12&\n" +
	"\x05rooms\x18\x01 \x03(\v2\x10.conference.RoomR\x05rooms\x12&\n" +
	"\x0fnext_room_token\x18\x02 \x01(\tR\rnextRoomToken\"+\n" +
	"\x10CloseRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x89\x01\n" +
	"\x16CreateJoinTokenRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.conference.RoleR\x04role\x12\x17\n" +
	"\attl_sec\x18\x04 \x01(\x05R\x06ttlSec\"/\n" +
	"\x17CreateJoinTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05tokenBGZEgithub.com/junhekdevsru/omega-zoom-no/api/proto/conference;conferenceb\x06proto3"

var (
	file_conference_room_proto_rawDescOnce sync.Once
	file_conference_room_proto_rawDescData []byte
)

func file_conference_room_proto_rawDescGZIP() []byte {
	file_conference_room_proto_rawDescOnce.Do(func() {
		file_conference_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conference_room_proto_rawDesc), len(file_conference_room_proto_rawDesc)))
	})
	return file_conference_room_proto_rawDescData
}

var file_conference_room_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_conference_room_proto_goTypes = []any{
	(*Room)(nil),                    // 0: conference.Room
	(*Member)(nil),                  // 1: conference.Member
	(*CreateRoomRequest)(nil),       // 2: conference.CreateRoomRequest
	(*GetRoomResponse)(nil),         // 3: conference.GetRoomResponse
	(*ListRoomsRequest)(nil),        // 4: conference.ListRoomsRequest
	(*ListRoomsResponse)(nil),       // 5: conference.ListRoomsResponse
	(*CloseRoomRequest)(nil),        // 6: conference.CloseRoomRequest
	(*CreateJoinTokenRequest)(nil),  // 7: conference.CreateJoinTokenRequest
	(*CreateJoinTokenResponse)(nil), // 8: conference.CreateJoinTokenResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
	(Role)(0),                       // 10: conference.Role
}
var file_conference_room_proto_depIdxs = []int32{
	9,  // 0: conference.Room.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: conference.Room.updated_at:type_name -> google.protobuf.Timestamp
	10, // 2: conference.Member.role:type_name -> conference.Role
	9,  // 3: conference.Member.joined_at:type_name -> google.protobuf.Timestamp
	9,  // 4: conference.Member.left_at:type_name -> google.protobuf.Timestamp
	0,  // 5: conference.GetRoomResponse.room:type_name -> conference.Room
	0,  // 6: conference.ListRoomsResponse.rooms:type_name -> conference.Room
	10, // 7: conference.CreateJoinTokenRequest.role:type_name -> conference.Role
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_conference_room_proto_init() }
func file_conference_room_proto_init() {
	if File_conference_room_proto != nil {
		return
	}
	file_conference_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conference_room_proto_rawDesc), len(file_conference_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conference_room_proto_goTypes,
		DependencyIndexes: file_conference_room_proto_depIdxs,
		MessageInfos:      file_conference_room_proto_msgTypes,
	}.Build()
	File_conference_room_proto = out.File
	file_conference_room_proto_goTypes = nil
	file_conference_room_proto_depIdxs = nil
}
