name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}   # ручной запуск через UI

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf
          buf --version

      - name: Generate proto
        run: |
          chmod +x ./easyp
          ./easyp mod vendor
          ./easyp generate

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race ./...
